[package]
name = "rhttp"
version = "0.1.0"
authors = ["AliAlboainin96 <alialboainin2005@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
